// Generated by CoffeeScript 1.4.0
(function() {
  var CountryActiveCtrl,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CountryActiveCtrl = (function(_super) {

    __extends(CountryActiveCtrl, _super);

    function CountryActiveCtrl() {
      this.bindCountryChange = __bind(this.bindCountryChange, this);
      __Model.Country.bind("change", this.bindCountryChange);
      __Model.Country.bind("active", this.refreshActive);
    }

    CountryActiveCtrl.prototype.bindCountryChange = function(country) {
      if (country.isActive()) {
        return this.refreshActive(country);
      }
    };

    CountryActiveCtrl.prototype.refreshActive = function(country) {
      var view;
      view = new __View.CountryPrima({
        model: country
      });
      return view.html(country);
    };

    return CountryActiveCtrl;

  })(Monocle.Controller);

  __Controller.CountryActive = new CountryActiveCtrl("section#section-prima-country");

}).call(this);
