// Generated by CoffeeScript 1.4.0
(function() {
  var CountryService,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CountryService = (function(_super) {

    __extends(CountryService, _super);

    function CountryService() {
      this;

    }

    return CountryService;

  })(Monocle.Controller);

}).call(this);
