// Generated by CoffeeScript 1.4.0
(function() {
  var CountryLstCtrl,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CountryLstCtrl = (function(_super) {

    __extends(CountryLstCtrl, _super);

    function CountryLstCtrl() {
      this.bindCountryChange = __bind(this.bindCountryChange, this);

      this.bindCountryCreate = __bind(this.bindCountryCreate, this);
      CountryLstCtrl.__super__.constructor.apply(this, arguments);
      __Model.Country.bind("create", this.bindCountryCreate);
      __Model.Country.bind("change", this.bindCountryChange);
    }

    CountryLstCtrl.prototype.bindCountryCreate = function(country) {
      var view;
      console.error("country created: ", country);
      view = new __View.Countryli({
        model: country
      });
      return view.append(country);
    };

    CountryLstCtrl.prototype.bindCountryChange = function(country) {
      console.error("country changed: ", country);
      return this;
    };

    return CountryLstCtrl;

  })(Monocle.Controller);

  __Controller.CountryLst = new CountryLstCtrl("article#all-primas");

}).call(this);
