// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.App.Animations = (function(lng, $) {
    var ANIMATIONS_END_EVENTS, init, _onAnimationEnd;
    ANIMATIONS_END_EVENTS = ["webkitAnimationEnd", "animationend"];
    init = function() {
      var $body, event, _i, _len, _results;
      $body = lng.dom("body");
      _results = [];
      for (_i = 0, _len = ANIMATIONS_END_EVENTS.length; _i < _len; _i++) {
        event = ANIMATIONS_END_EVENTS[_i];
        _results.push($body.delegate("[data-animation]", event, _onAnimationEnd));
      }
      return _results;
    };
    _onAnimationEnd = function(event) {
      var $el;
      $el = lng.dom(event.target);
      $el.removeAttr("data-animation-direction");
      $el.removeClass("animating");
      return console.warn("animationEnd in ", $el);
    };
    $.fn.animate = function(animation, direction) {
      return this.data("animation", animation).data("animation-direction", direction).addClass("animating");
    };
    return {
      init: init
    };
  })(Lungo, Quo);

}).call(this);
