// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.App = (function(lng) {
    lng.init({
      name: "Mira la Prima",
      version: "2.0",
      resources: ["app/resources/sections/country.html", "app/resources/sections/uploadprima.html", "app/resources/sections/about.html"]
    });
    lng.ready(function() {
      if (root.Device.isFree()) {
        $$("#section-prima-country .country-view-mode").hide();
        $$("#section-prima-country footer").addClass("transparent-footer");
        $$("body").addClass("free-version");
      }
      if (!lng.Core.environment().isMobile) {
        $$("#share-btn").parent().hide();
        return $$("body").addClass("not-mobile");
      }
    });
    return {};
  })(Lungo);

}).call(this);
