// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.App.Help = (function(lng) {
    var hide, show, _container, _init;
    _container = lng.dom("<div></div>");
    show = function(html) {
      _container.html(html);
      return _container.show();
    };
    _init = function() {
      lng.dom("body").append(_container[0]);
      _container.hide();
      _container.style("position", "absolute");
      _container.style("width", "100%");
      _container.style("height", "100%");
      _container.style("z-index", "5");
      _container.style("background", "none");
      return _container.style("background-color", "rgba(0, 0, 0, 0.8)");
    };
    hide = function() {
      return _container.hide();
    };
    lng.ready(function() {
      return _init();
    });
    return {
      show: show,
      hide: hide
    };
  })(Lungo);

}).call(this);
