// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  __Model.Country = (function(_super) {

    __extends(Country, _super);

    function Country() {
      return Country.__super__.constructor.apply(this, arguments);
    }

    Country.fields("name", "country_code", "prima_value", "prima_delta", "prima_percent", "last_update");

    return Country;

  })(Monocle.Model);

}).call(this);
